on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  runs-on: ubuntu-latest

  matrix:
    command:
      - lint:eslint
      - lint:prettier
      - test
    fast-fail: false

  check:
    steps:

      - uses: action/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true

      - run: pnpm ${{ matrix.command }}
