on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint:eslint
          - lint:prettier
          - test
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true

      - run: pnpm ${{ matrix.command }}
